apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: smartseller-storefront-backendconfig
  namespace: smartseller
spec:
  healthCheck:
    requestPath: /health
    port: 5173
    type: HTTP