apiVersion: v1
kind: Secret
metadata:
  name: smartseller-db
  namespace: smartseller
type: Opaque
stringData:
  DB_USER: smartseller_user
  DB_PASSWORD: smartseller_pass
  DB_NAME: smartseller_db
  INSTANCE_CONNECTION_NAME: kirimku-475304:asia-southeast2:kirimku